
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author asus
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtnomor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtJudul = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tglPinjam = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        tglKembali = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        rdsudah = new javax.swing.JRadioButton();
        rdbelum = new javax.swing.JRadioButton();
        cbJenis = new javax.swing.JComboBox<>();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel3.setBackground(new java.awt.Color(204, 159, 45));
        jPanel3.setLayout(null);

        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No Anggota", "Nama Peminjam", "Alamat Peminjam", "Jenis Buku", "Judul Buku", "Tanggal Pinjam", "Tanggal Kembali", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblData.getTableHeader().setReorderingAllowed(false);
        tblData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblData);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(20, 290, 820, 190);

        jButton1.setFont(new java.awt.Font("Square721 BT", 0, 12)); // NOI18N
        jButton1.setText("Simpan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(430, 120, 190, 40);

        jButton2.setFont(new java.awt.Font("Square721 BT", 0, 12)); // NOI18N
        jButton2.setText("Besihkan");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(660, 120, 180, 40);

        jButton3.setFont(new java.awt.Font("Square721 BT", 0, 12)); // NOI18N
        jButton3.setText("Refresh");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(430, 180, 190, 40);

        jButton4.setFont(new java.awt.Font("Square721 BT", 0, 12)); // NOI18N
        jButton4.setText("Print");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4);
        jButton4.setBounds(660, 180, 180, 40);

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel1.setText("No Anggota");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(20, 20, 80, 20);
        jPanel3.add(txtnomor);
        txtnomor.setBounds(20, 40, 180, 30);

        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel2.setText("Nama Peminjam");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(20, 70, 100, 40);
        jPanel3.add(txtNama);
        txtNama.setBounds(20, 100, 180, 30);

        jLabel4.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel4.setText("Alamat Peminjam");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(20, 134, 150, 30);

        txtAlamat.setColumns(20);
        txtAlamat.setRows(5);
        jScrollPane2.setViewportView(txtAlamat);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(20, 160, 180, 120);

        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel3.setText("Jenis  Buku");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(230, 14, 120, 30);

        jLabel8.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel8.setText("Judul Buku");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(230, 70, 80, 30);
        jPanel3.add(txtJudul);
        txtJudul.setBounds(230, 100, 160, 30);

        jLabel7.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel7.setText("Tanggal Pinjam");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(230, 130, 110, 40);
        jPanel3.add(tglPinjam);
        tglPinjam.setBounds(230, 170, 160, 30);

        jLabel6.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel6.setText("Tanggal Kembali");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(230, 200, 100, 50);
        jPanel3.add(tglKembali);
        tglKembali.setBounds(230, 250, 160, 30);

        jLabel5.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel5.setText("Status");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(430, 20, 100, 30);

        buttonGroup1.add(rdsudah);
        rdsudah.setText("Sudah Kembali");
        jPanel3.add(rdsudah);
        rdsudah.setBounds(430, 50, 190, 23);

        buttonGroup1.add(rdbelum);
        rdbelum.setText("Belum Kembali");
        jPanel3.add(rdbelum);
        rdbelum.setBounds(430, 70, 190, 23);

        cbJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Jenis Buku", "Pelajaran", "Fiksi", "Nonfiksi" }));
        cbJenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbJenisActionPerformed(evt);
            }
        });
        jPanel3.add(cbJenis);
        cbJenis.setBounds(230, 40, 160, 30);

        jButton6.setFont(new java.awt.Font("Square721 BT", 0, 12)); // NOI18N
        jButton6.setText("Hapus");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6);
        jButton6.setBounds(430, 240, 190, 40);

        jButton7.setFont(new java.awt.Font("Square721 BT", 0, 12)); // NOI18N
        jButton7.setText("Keluar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton7);
        jButton7.setBounds(660, 240, 180, 40);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 120, 900, 520);

        jPanel1.setBackground(new java.awt.Color(205, 92, 36));
        jPanel1.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Lighthouse Personal Use", 1, 72)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 0));
        jLabel9.setText("Apps");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(500, 30, 270, 80);

        jLabel10.setFont(new java.awt.Font("Lighthouse Personal Use", 1, 72)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Library");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(250, 30, 270, 80);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-10, -9, 890, 130);

        setBounds(0, 0, 888, 668);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        txtnomor.setText("");
        txtNama.setText("");
        txtAlamat.setText("");
        cbJenis.setSelectedItem("Pilih Jenis Buku");
        txtJudul.setText("");
        buttonGroup1.clearSelection();
        tglPinjam.cleanup();
        tglKembali.cleanup();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
       String pinjam = dateFormat.format(tglPinjam.getDate());
       String kembali = dateFormat.format(tglKembali.getDate());
       String Status = "";
           if(rdsudah.isSelected()){
           }else{
               Status = "Sudah Kembali";
           }
           if(rdbelum.isSelected()){
               Status = "Belum Kembali";
           }
        
        if ("".equals(txtnomor.getText()) || "".equals(txtNama.getText()) ||"".equals(txtAlamat.getText()) || 
                 "".equals(cbJenis.getSelectedItem()) || "".equals(txtJudul.getText()) || "".equals(pinjam) || "".equals(kembali)){
            JOptionPane.showMessageDialog(this,"Harap Lengkapi Data!","Error",JOptionPane.WARNING_MESSAGE);
       }else{
           
           String SQL = "INSERT INTO t_siswa (NoAnggota,NamaPeminjam,AlamatPeminjam,JenisBuku,JudulBuku,TanggalPinjam,TanggalKembali,Status)"
                + "VALUES ('"+txtnomor.getText()+"','"+txtNama.getText()+"','"+txtAlamat.getText()+"','"+cbJenis.getSelectedItem()+"','"
                   +txtJudul.getText()+"','"+pinjam+"','"+kembali+"','"+Status+"')";
        int status = KoneksiDB.execute(SQL);
        if (status == 1){
            JOptionPane.showMessageDialog(this,"Data Berhasil Ditambahkan","Sukses",JOptionPane.INFORMATION_MESSAGE);
            selectData();
        }else{
            JOptionPane.showMessageDialog(this,"Data Gagal Ditambahkan","Error",JOptionPane.WARNING_MESSAGE);
        }
            
        
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void cbJenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJenisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbJenisActionPerformed

    private void tblDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDataMouseClicked
        int baris = tblData.getSelectedRow();
        if (baris != -1){
            txtnomor.setText(tblData.getValueAt(baris, 0).toString());
            txtNama.setText(tblData.getValueAt(baris, 1).toString());
            txtAlamat.setText(tblData.getValueAt(baris, 2).toString());
            txtJudul.setText(tblData.getValueAt(baris, 4).toString());
            if("Sudah Kembali".equals(tblData.getValueAt(baris, 7).toString())){
                rdsudah.setSelected(true);
            }else{
                rdbelum.setSelected(true);
            }
        }
    }//GEN-LAST:event_tblDataMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        selectData();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        int baris = tblData.getSelectedRow();
        if (baris != -1){
            String NoAnggota = tblData.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM t_siswa WHERE NoAnggota = '"+NoAnggota+"'";
            int status = KoneksiDB.execute(SQL);
            if (status == 1){
                JOptionPane.showMessageDialog(null,"Data Berhasil Dihapus","Sukses",JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(null,"Data Gagal Dihapus","Gagal",JOptionPane.WARNING_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null,"Pilih Baris Data Terlebih Dahulu","Error",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        MessageFormat header = new MessageFormat("");
        MessageFormat footer = new MessageFormat("Page (0,number,integer)");
        try{
            tblData.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
        }catch(java.awt.print.PrinterException e){
            System.err.format("Cannot print %s%n", e.getMessage());
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    public void selectData(){
        String kolom[] = {"NoAnggota","NamaPeminjam","AlamatPeminjam","JenisBuku","JudulBuku","TanggalPinjam","TanggalKembali","Status"};
            DefaultTableModel dtm = new DefaultTableModel(null, kolom);
            String SQL = "SELECT * FROM t_siswa";
            ResultSet rs = KoneksiDB.executeQuery(SQL);
            try{
                while(rs.next()){
                    String NoAnggota = rs.getString(1);
                    String NamaPeminjam = rs.getString(2);
                    String AlamatPeminjam = rs.getString(3);
                    String JenisBuku = "";
                    if("".equals(rs.getString(4))){
                        JenisBuku = "Pelajaran";
                    }else{
                        JenisBuku = "Fiksi";
                    }
                    String JudulBuku = rs.getString(5);
                    String TanggalPinjam = rs.getString(6);
                    String TanggalKembali = rs.getString(7);
                    String Status = rs.getString(8);
                    
                    String data[] = {NoAnggota,NamaPeminjam,AlamatPeminjam,JenisBuku,JudulBuku,TanggalPinjam,TanggalKembali,Status};
                    dtm.addRow(data);
                }
            }catch(SQLException ex){
                Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
            }
            tblData.setModel(dtm);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbJenis;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rdbelum;
    private javax.swing.JRadioButton rdsudah;
    private javax.swing.JTable tblData;
    private com.toedter.calendar.JDateChooser tglKembali;
    private com.toedter.calendar.JDateChooser tglPinjam;
    private javax.swing.JTextArea txtAlamat;
    private javax.swing.JTextField txtJudul;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtnomor;
    // End of variables declaration//GEN-END:variables
}
